version: "2"
services:
  web:
    image: shrikrishna/diaspora:dockerfile
    command: '/bin/bash -l -c "bundle exec unicorn -c config/unicorn.rb"'
    # links:
    #   - db
    #   - redis
  db:
    image: postgres:latest
  redis:
    image: redis:latest
