version: "2"
services:
  web:
    environment:
      - RAILS_ENV=development
    volumes:
      - '${DIASPORA_DIR}/diaspora.yml:/home/diaspora/diaspora/config/diaspora.yml'
      - '${DIASPORA_DIR}/database.yml:/home/diaspora/database/config/database.yml'
    links:
      - db
  nginx:
    image: nginx:alpine
    volumes:
      - '${DIASPORA_DIR}/nginx.conf:/etc/nginx/nginx.conf'
      - '${DIASPORA_DIR}/public:/srv/public'
    ports:
      - "80:80"
    links:
      - web
