version: "2"
services:
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - "./config/diaspora.yml:/home/diaspora/diaspora/config/diaspora.yml"
      - "./config/database.yml:/home/diaspora/diaspora/config/database.yml"
